import io

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN


def build_pptx(outline: dict) -> bytes:
    """Build a PPTX from a structured outline dict.

    Expected format:
    {
        "title": "Presentation Title",
        "slides": [
            {
                "title": "Slide Title",
                "bullet_points": ["Point 1", "Point 2"],
                "speaker_notes": "Notes here"
            }
        ]
    }
    """
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    title_text = outline.get("title", "Presentation")
    slides_data = outline.get("slides", [])

    # Limit slides
    if len(slides_data) > 30:
        slides_data = slides_data[:30]

    # Title slide
    _add_title_slide(prs, title_text)

    # Content slides
    for slide_data in slides_data:
        _add_content_slide(prs, slide_data)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


def _add_title_slide(prs: Presentation, title: str):
    slide_layout = prs.slide_layouts[0]  # Title Slide
    slide = prs.slides.add_slide(slide_layout)

    if slide.placeholders:
        slide.placeholders[0].text = title
        if len(slide.placeholders) > 1:
            slide.placeholders[1].text = "Generated by Planar"

    # Style the title
    for placeholder in slide.placeholders:
        for paragraph in placeholder.text_frame.paragraphs:
            paragraph.alignment = PP_ALIGN.CENTER
            for run in paragraph.runs:
                run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)


def _add_content_slide(prs: Presentation, slide_data: dict):
    slide_layout = prs.slide_layouts[1]  # Title and Content
    slide = prs.slides.add_slide(slide_layout)

    title = slide_data.get("title", "")
    bullets = slide_data.get("bullet_points", [])
    notes = slide_data.get("speaker_notes", "")

    # Set title
    if slide.placeholders:
        slide.placeholders[0].text = title[:200]  # Length limit
        for paragraph in slide.placeholders[0].text_frame.paragraphs:
            for run in paragraph.runs:
                run.font.size = Pt(28)
                run.font.color.rgb = RGBColor(0x1A, 0x1A, 0x2E)

    # Set bullet points
    if len(slide.placeholders) > 1:
        tf = slide.placeholders[1].text_frame
        tf.clear()
        for i, bullet in enumerate(bullets[:10]):  # Max 10 bullets
            if i == 0:
                tf.paragraphs[0].text = bullet[:500]
            else:
                p = tf.add_paragraph()
                p.text = bullet[:500]
            para = tf.paragraphs[i]
            para.space_after = Pt(6)
            for run in para.runs:
                run.font.size = Pt(18)
                run.font.color.rgb = RGBColor(0x33, 0x33, 0x33)

    # Speaker notes
    if notes:
        notes_slide = slide.notes_slide
        notes_slide.notes_text_frame.text = notes[:2000]
